/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as PosterNewRouteImport } from './routes/poster/new'
import { Route as PosterLayoutRouteImport } from './routes/poster/_layout'
import { Route as PosterIdDetailRouteImport } from './routes/poster/$id.detail'

const PosterRouteImport = createFileRoute('/poster')()

const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterNewRoute = PosterNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PosterRoute,
} as any)
const PosterLayoutRoute = PosterLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PosterRoute,
} as any)
const PosterIdDetailRoute = PosterIdDetailRouteImport.update({
  id: '/$id/detail',
  path: '/$id/detail',
  getParentRoute: () => PosterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poster': typeof PosterLayoutRoute
  '/poster/new': typeof PosterNewRoute
  '/gallery': typeof GalleryIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/poster/$id/detail': typeof PosterIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poster': typeof PosterLayoutRoute
  '/poster/new': typeof PosterNewRoute
  '/gallery': typeof GalleryIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/poster/$id/detail': typeof PosterIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poster': typeof PosterRouteWithChildren
  '/poster/_layout': typeof PosterLayoutRoute
  '/poster/new': typeof PosterNewRoute
  '/gallery/': typeof GalleryIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/poster/$id/detail': typeof PosterIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/poster'
    | '/poster/new'
    | '/gallery'
    | '/prompts'
    | '/poster/$id/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/poster'
    | '/poster/new'
    | '/gallery'
    | '/prompts'
    | '/poster/$id/detail'
  id:
    | '__root__'
    | '/'
    | '/poster'
    | '/poster/_layout'
    | '/poster/new'
    | '/gallery/'
    | '/prompts/'
    | '/poster/$id/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PosterRoute: typeof PosterRouteWithChildren
  GalleryIndexRoute: typeof GalleryIndexRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/new': {
      id: '/poster/new'
      path: '/new'
      fullPath: '/poster/new'
      preLoaderRoute: typeof PosterNewRouteImport
      parentRoute: typeof PosterRoute
    }
    '/poster/_layout': {
      id: '/poster/_layout'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterLayoutRouteImport
      parentRoute: typeof PosterRoute
    }
    '/poster/$id/detail': {
      id: '/poster/$id/detail'
      path: '/$id/detail'
      fullPath: '/poster/$id/detail'
      preLoaderRoute: typeof PosterIdDetailRouteImport
      parentRoute: typeof PosterRoute
    }
  }
}

interface PosterRouteChildren {
  PosterLayoutRoute: typeof PosterLayoutRoute
  PosterNewRoute: typeof PosterNewRoute
  PosterIdDetailRoute: typeof PosterIdDetailRoute
}

const PosterRouteChildren: PosterRouteChildren = {
  PosterLayoutRoute: PosterLayoutRoute,
  PosterNewRoute: PosterNewRoute,
  PosterIdDetailRoute: PosterIdDetailRoute,
}

const PosterRouteWithChildren =
  PosterRoute._addFileChildren(PosterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PosterRoute: PosterRouteWithChildren,
  GalleryIndexRoute: GalleryIndexRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
